const C = {
  TRANS: [0, 0, 0, 0],
  DGREN: [46, 125, 50, 255],
  GREEN: [76, 175, 80, 255],
  BROWN: [139, 69, 19, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
};

export const goblinSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DGREN,C.DGREN,C.DGREN,C.DGREN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.BLACK, C.BLACK, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.GREEN,  C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.BLACK, C.GREEN,  C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.DGREN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DGREN,C.DGREN,C.DGREN,C.BROWN,  C.BROWN,   C.BROWN, C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN, C.BROWN,  C.TRANS, C.TRANS, C.TRANS],
  [C.DGREN,C.BROWN,  C.DGREN,C.BROWN,  C.BROWN,   C.BROWN, C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN, C.BROWN,  C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DGREN,C.TRANS, C.DGREN,C.DGREN,C.BROWN,  C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.DGREN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.DGREN, C.TRANS, C.TRANS, C.BROWN,   C.BROWN,   C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DGREN,C.DGREN,C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DGREN,C.DGREN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
