const C = {
  TRANS: [0, 0, 0, 0],
  RED:   [178, 34, 34, 255],
  DK_RED:[139, 0, 0, 255],
  BROWN: [139, 69, 19, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
};

export const orcSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.RED, C.BLACK, C.BLACK, C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.RED, C.RED,  C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.RED, C.BLACK, C.RED,  C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.TRANS, C.RED,   C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_RED,C.DK_RED,C.DK_RED,C.BROWN,  C.BROWN,   C.BROWN, C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN, C.BROWN,  C.TRANS, C.TRANS, C.TRANS],
  [C.DK_RED,C.BROWN,  C.DK_RED,C.BROWN,  C.BROWN,   C.BROWN, C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN, C.BROWN,  C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DK_RED,C.TRANS, C.DK_RED,C.DK_RED,C.BROWN,  C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.BROWN,   C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.DK_RED, C.TRANS, C.TRANS, C.BROWN,   C.BROWN,   C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BROWN,   C.BROWN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
