const C = {
  TRANS: [0, 0, 0, 0],
  GRAY:  [169, 169, 169, 255],
  DK_GRY:[105, 105, 105, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
};

export const skeletonSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GRAY, C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GRAY,   C.GRAY, C.BLACK, C.BLACK, C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GRAY,   C.GRAY, C.GRAY,  C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GRAY,   C.GRAY, C.BLACK, C.GRAY,  C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.GRAY, C.TRANS, C.TRANS, C.GRAY,   C.GRAY, C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY,   C.GRAY, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.GRAY, C.TRANS, C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.DK_GRY,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_GRY,C.DK_GRY,C.DK_GRY,C.WHITE, C.WHITE,  C.WHITE,C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE, C.WHITE, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_GRY,C.WHITE, C.DK_GRY,C.WHITE, C.WHITE,  C.WHITE,C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE, C.WHITE, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DK_GRY,C.TRANS, C.DK_GRY,C.DK_GRY,C.WHITE, C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.WHITE,  C.DK_GRY,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.WHITE,  C.WHITE,C.DK_GRY, C.TRANS, C.TRANS, C.WHITE,  C.WHITE,  C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.WHITE,  C.WHITE,C.TRANS,  C.TRANS,  C.TRANS,  C.TRANS,  C.WHITE,  C.WHITE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRY, C.DK_GRY, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRY, C.DK_GRY, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
