const C = {
  TRANS: [0, 0, 0, 0],
  BLUE:  [30, 144, 255, 255],
  DK_BLU:[0, 0, 139, 255],
  BROWN: [139, 69, 19, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
  SKIN:  [255, 224, 189, 255],
  GOLD:  [255, 215, 0, 255],
};

export const mageSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BLUE, C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.GOLD, C.TRANS, C.TRANS, C.BLUE,   C.BLUE, C.BLACK, C.BLACK, C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.GOLD, C.TRANS, C.TRANS, C.BLUE,   C.SKIN,C.SKIN,  C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.GOLD, C.TRANS, C.TRANS, C.BLUE,   C.SKIN,C.BLACK, C.SKIN,  C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.TRANS, C.BLUE,   C.BLUE, C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.DK_BLU,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_BLU,C.DK_BLU,C.DK_BLU,C.BLUE,  C.BLUE,   C.BLUE, C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.BLUE,  C.TRANS, C.TRANS, C.TRANS],
  [C.DK_BLU,C.BLUE,  C.DK_BLU,C.BLUE,  C.BLUE,   C.BLUE, C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE, C.BLUE,  C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DK_BLU,C.TRANS, C.DK_BLU,C.DK_BLU,C.BLUE,  C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.BLUE,   C.DK_BLU,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BLUE,   C.BLUE, C.DK_BLU, C.TRANS, C.TRANS, C.BLUE,   C.BLUE,   C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.BLUE,   C.BLUE, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_BLU,C.DK_BLU,C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_BLU,C.DK_BLU,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
