const C = {
  TRANS: [0, 0, 0, 0],
  GREEN: [34, 139, 34, 255],
  DK_GRN:[0, 100, 0, 255],
  BROWN: [139, 69, 19, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
  SKIN:  [255, 224, 189, 255],
};

export const rogueSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.BLACK, C.BLACK, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.SKIN,C.SKIN,  C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.GREEN,   C.SKIN,C.BLACK, C.SKIN,  C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.DK_GRN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_GRN,C.DK_GRN,C.DK_GRN,C.GREEN,  C.GREEN,   C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.GREEN,  C.TRANS, C.TRANS, C.TRANS],
  [C.DK_GRN,C.GREEN,  C.DK_GRN,C.GREEN,  C.GREEN,   C.GREEN, C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN, C.GREEN,  C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DK_GRN,C.TRANS, C.DK_GRN,C.DK_GRN,C.GREEN,  C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.GREEN,   C.DK_GRN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.DK_GRN, C.TRANS, C.TRANS, C.GREEN,   C.GREEN,   C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.GREEN,   C.GREEN, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRN,C.DK_GRN,C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_GRN,C.DK_GRN,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
