const C = {
  TRANS: [0, 0, 0, 0],
  RED:   [220, 20, 60, 255],
  DK_RED:[139, 0, 0, 255],
  BROWN: [139, 69, 19, 255],
  BLACK: [0, 0, 0, 255],
  WHITE: [255, 255, 255, 255],
  SKIN:  [255, 224, 189, 255],
};

export const warriorSprite = [
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.RED, C.BLACK, C.BLACK, C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.SKIN,C.SKIN,  C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.WHITE,C.TRANS, C.TRANS, C.RED,   C.SKIN,C.BLACK, C.SKIN,  C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.TRANS, C.RED,   C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.BROWN,C.TRANS, C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.DK_RED,C.DK_RED,C.DK_RED,C.RED,  C.RED,   C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.RED,  C.TRANS, C.TRANS, C.TRANS],
  [C.DK_RED,C.RED,  C.DK_RED,C.RED,  C.RED,   C.RED, C.RED,   C.RED,   C.RED,   C.RED,   C.RED,   C.RED, C.RED,  C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.DK_RED,C.TRANS, C.DK_RED,C.DK_RED,C.RED,  C.RED,   C.RED,   C.RED,   C.RED,   C.RED,   C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.RED,   C.RED, C.DK_RED, C.TRANS, C.TRANS, C.RED,   C.RED,   C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.RED,   C.RED, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.DK_RED,C.DK_RED,C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS],
  [C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS, C.TRANS]
];
